### ISSUE TITLE
Mapping over a tuple

### ISSUE THREAD

**Issue by torkleyy** [s3bk/tuple#1]
Not sure if this is possible with Rust macros at all, but I would like to create a tuple by calling a method on the elements of an existing tuple. So the expanded code would look lile

```rust
(self.0.foo(), self.1.foo(), self.2.foo(), ...)
```

**Comment by s3bk** [comment]
This is definitely possible, however it requires to specify the number of elements.
This could be done via `map!(old_tuple, 5, foo)` or `map5!(old_tuple, foo)`.

If all elements have the same type, then you can already use `old_tuple.map(|x| x.foo())`

**Comment by torkleyy** [comment]
Ah I see, thank you!
