### ISSUE TITLE
Stable support

### ISSUE THREAD

**Issue by Lukazoid** [s3bk/tuple#2]
Currently this crate cannot be used on stable due to the use of `#![feature(...)]`. Would it be feasible for nightly features to be optional so we may use this crate on stable?

**Comment by s3bk** [comment]
It is indeed possible. https://github.com/s3bk/tuple/commit/8a18a01bfc4987b6a56fd7741b8d1e31ff7890b2 works on stable (without the impl_simd feature).

**Comment by s3bk** [comment]
```
[dependencies]
tuple = "0.3.8"
```
should work now!

**Comment by Lukazoid** [comment]
Can confirm, it's working for me on stable now, thanks @s3bk !

**Comment by pravic** [comment]
Hi! I am curious about those `feature="nightly"` blocks. They were not declared in Cargo.toml, is this by intention?

**Comment by s3bk** [comment]
@pravic Good catch.
